<Project Sdk="Microsoft.NET.Sdk">

  <!-- Quick tests of OOPLAB1 without any test library; how to run them is written in Program.cs -->

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OOPLAB1\OOPLAB1.csproj" />
  </ItemGroup>

</Project>
